/**
 * 精选字信息（部首/结构）。仅收录可确证的常用字；未收录字段留空（不展示错误信息）。
 * 结构：字 -> [部首, 结构]
 */
export const CHAR_META: Record<string, [string, string]> = {
  一: ['一', 'single'], 二: ['二', 'single'], 三: ['三', 'single'], 四: ['囗', 'enclosure'],
  五: ['二', 'top_bottom'], 六: ['八', 'top_bottom'], 七: ['一', 'single'], 八: ['八', 'single'],
  九: ['乙', 'single'], 十: ['十', 'single'], 百: ['白', 'top_bottom'], 千: ['十', 'top_bottom'],
  万: ['一', 'single'], 元: ['二', 'top_bottom'], 角: ['角', 'top_bottom'], 分: ['八', 'top_bottom'],
  上: ['一', 'single'], 下: ['一', 'single'], 中: ['丨', 'single'], 前: ['刂', 'top_bottom'],
  后: ['口', 'enclosure'], 左: ['工', 'single'], 右: ['口', 'enclosure'], 东: ['一', 'single'],
  西: ['覀', 'enclosure'], 南: ['十', 'top_bottom'], 北: ['匕', 'top_bottom'],
  大: ['大', 'single'], 小: ['小', 'single'], 多: ['夕', 'top_bottom'], 少: ['小', 'single'],
  高: ['高', 'top_bottom'], 低: ['亻', 'left_right'], 长: ['长', 'single'], 短: ['矢', 'left_right'],
  远: ['辶', 'enclosure'], 近: ['辶', 'enclosure'],
  开: ['廾', 'top_bottom'], 关: ['丷', 'top_bottom'], 来: ['木', 'single'], 去: ['土', 'top_bottom'],
  出: ['凵', 'top_bottom'], 入: ['入', 'single'], 进: ['辶', 'enclosure'], 退: ['辶', 'enclosure'],
  回: ['囗', 'enclosure'], 过: ['辶', 'enclosure'], 站: ['立', 'left_right'], 坐: ['土', 'top_bottom'],
  没: ['氵', 'left_right'], 在: ['土', 'enclosure'], 有: ['月', 'top_bottom'], 的: ['白', 'left_right'],
  了: ['乙', 'single'], 和: ['口', 'left_right'], 与: ['一', 'single'], 就: ['尤', 'left_right'],
  都: ['阝', 'left_right'], 也: ['乙', 'single'], 很: ['彳', 'left_right'], 再: ['冂', 'single'],
  见: ['见', 'top_bottom'], 看: ['目', 'top_bottom'], 听: ['口', 'left_right'], 说: ['讠', 'left_right'],
  读: ['讠', 'left_right'], 走: ['走', 'top_bottom'], 跑: ['足', 'left_right'], 跳: ['足', 'left_right'],
  飞: ['飞', 'single'], 你: ['亻', 'left_right'], 我: ['戈', 'single'], 他: ['亻', 'left_right'],
  她: ['女', 'left_right'], 它: ['宀', 'top_bottom'], 们: ['亻', 'left_right'], 人: ['人', 'single'],
  爸: ['父', 'top_bottom'], 妈: ['女', 'left_right'], 爷: ['父', 'top_bottom'], 奶: ['女', 'left_right'],
  哥: ['口', 'top_bottom'], 姐: ['女', 'left_right'], 弟: ['弓', 'top_bottom'], 妹: ['女', 'left_right'],
  儿: ['儿', 'single'], 子: ['子', 'single'], 女: ['女', 'single'], 男: ['田', 'top_bottom'],
  老: ['老', 'top_bottom'], 师: ['巾', 'left_right'], 生: ['生', 'single'], 朋: ['月', 'left_right'],
  友: ['又', 'top_bottom'], 口: ['口', 'single'], 家: ['宀', 'top_bottom'], 天: ['大', 'single'],
  地: ['土', 'left_right'], 水: ['水', 'single'], 火: ['火', 'single'], 山: ['山', 'single'],
  石: ['石', 'single'], 田: ['田', 'single'], 土: ['土', 'single'], 金: ['金', 'top_bottom'],
  木: ['木', 'single'], 日: ['日', 'single'], 月: ['月', 'single'], 星: ['日', 'top_bottom'],
  云: ['二', 'top_bottom'], 雨: ['雨', 'single'], 风: ['风', 'enclosure'], 雪: ['雨', 'top_bottom'],
  电: ['电', 'single'], 闪: ['门', 'enclosure'], 光: ['光', 'top_bottom'], 明: ['日', 'left_right'],
  亮: ['亠', 'top_bottom'], 早: ['日', 'top_bottom'], 晚: ['日', 'left_right'], 午: ['十', 'single'],
  夜: ['亠', 'top_bottom'], 今: ['人', 'top_bottom'], 年: ['年', 'single'], 时: ['日', 'left_right'],
  秒: ['禾', 'left_right'],
  花: ['艹', 'top_bottom'], 草: ['艹', 'top_bottom'], 树: ['木', 'left_right'], 叶: ['口', 'left_right'],
  林: ['木', 'left_right'], 森: ['木', 'top_bottom'], 枝: ['木', 'left_right'], 根: ['木', 'left_right'],
  果: ['木', 'top_bottom'], 米: ['米', 'single'], 豆: ['豆', 'single'], 瓜: ['瓜', 'single'],
  菜: ['艹', 'top_bottom'], 禾: ['禾', 'single'], 竹: ['竹', 'left_right'],
  猫: ['犭', 'left_right'], 狗: ['犭', 'left_right'], 鸟: ['鸟', 'single'], 鱼: ['鱼', 'top_bottom'],
  虫: ['虫', 'single'], 马: ['马', 'single'], 牛: ['牛', 'single'], 羊: ['羊', 'single'],
  猪: ['犭', 'left_right'], 鸡: ['又', 'left_right'], 鸭: ['甲', 'left_right'], 兔: ['刀', 'top_bottom'],
  虎: ['虎', 'enclosure'], 象: ['豕', 'single'], 狼: ['犭', 'left_right'], 猴: ['犭', 'left_right'],
  蛇: ['虫', 'left_right'], 龙: ['龙', 'single'], 蚂: ['虫', 'left_right'], 蚁: ['虫', 'left_right'],
  头: ['大', 'single'], 脸: ['月', 'left_right'], 眼: ['目', 'left_right'], 耳: ['耳', 'single'],
  鼻: ['鼻', 'top_bottom'], 牙: ['牙', 'single'], 手: ['手', 'single'], 足: ['足', 'top_bottom'],
  心: ['心', 'single'], 皮: ['皮', 'single'], 毛: ['毛', 'single'], 发: ['又', 'top_bottom'],
  骨: ['骨', 'top_bottom'], 目: ['目', 'single'], 唇: ['口', 'enclosure'],
  春: ['日', 'top_bottom'], 夏: ['夂', 'top_bottom'], 秋: ['禾', 'left_right'], 冬: ['夂', 'top_bottom'],
  床: ['广', 'enclosure'], 望: ['王', 'top_bottom'], 思: ['田', 'top_bottom'], 故: ['攵', 'left_right'],
  乡: ['乙', 'single'], 汗: ['氵', 'left_right'], 滴: ['氵', 'left_right'], 谁: ['讠', 'left_right'],
  盘: ['皿', 'top_bottom'], 粒: ['米', 'left_right'], 辛: ['辛', 'top_bottom'], 苦: ['艹', 'top_bottom'],
  曲: ['曰', 'single'], 项: ['工', 'left_right'], 歌: ['欠', 'left_right'], 浮: ['氵', 'left_right'],
  掌: ['手', 'top_bottom'], 拨: ['扌', 'left_right'], 波: ['氵', 'left_right'],
  必: ['心', 'single'], 方: ['方', 'single'], 里: ['里', 'single'], 垂: ['丿', 'single'],
  凹: ['凵', 'single'], 凸: ['凵', 'single'], 甩: ['用', 'single'], 肃: ['聿', 'top_bottom'],
  王: ['王', 'single'], 芳: ['艹', 'top_bottom'], 李: ['木', 'top_bottom'], 张: ['弓', 'left_right'],
  伟: ['亻', 'left_right'], 刘: ['刂', 'left_right'], 洋: ['氵', 'left_right'], 陈: ['阝', 'left_right'],
  静: ['青', 'left_right'], 杨: ['木', 'left_right'], 柳: ['木', 'left_right'], 赵: ['走', 'enclosure'],
  磊: ['石', 'top_bottom'], 孙: ['子', 'left_right'], 丽: ['一', 'top_bottom'], 周: ['冂', 'enclosure'],
  杰: ['木', 'top_bottom'], 吴: ['口', 'top_bottom'], 敏: ['攵', 'left_right'], 华: ['十', 'top_bottom'],
  冯: ['冫', 'left_right'], 刚: ['刂', 'left_right'], 梅: ['木', 'left_right'], 帆: ['巾', 'left_right'],
  朱: ['木', 'single'], 婷: ['女', 'left_right'], 秦: ['禾', 'top_bottom'], 岚: ['山', 'top_bottom'],
  许: ['讠', 'left_right'], 晨: ['日', 'top_bottom'], 何: ['亻', 'left_right'], 吕: ['口', 'top_bottom'],
  施: ['方', 'left_right'], 琦: ['王', 'left_right'], 娜: ['女', 'left_right'],
  白: ['白', 'single'], 红: ['纟', 'left_right'], 黄: ['黄', 'top_bottom'], 蓝: ['艹', 'top_bottom'],
  绿: ['纟', 'left_right'], 黑: ['黑', 'top_bottom'], 字: ['宀', 'top_bottom'], 学: ['子', 'top_bottom'],
  书: ['乙', 'single'], 本: ['木', 'single'], 笔: ['竹', 'top_bottom'], 纸: ['纟', 'left_right'],
  剪: ['刀', 'top_bottom'], 刀: ['刀', 'single'], 尺: ['尸', 'single'], 橡: ['木', 'left_right'],
  包: ['勹', 'enclosure'], 铅: ['钅', 'left_right'],
};
